<?php  //[STAMP] f1321cbe0be448cff310efa51f7c63db
namespace Eh\EhPhpunit\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
