<?php  //[STAMP] 39e33c1e939029d084b45b6f24caa112
namespace Eh\EhPhpunit\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
